### ISSUE TITLE
Figure with Link

### ISSUE THREAD

**Issue by romantoda** [pdf-association/Deriving-HTML-from-PDF#38]
The usual tagging for Image with link would be
```
<Figure>
    <Link>
        Content
```
in case of inline image, current text isn't clear about the link becoming a parent of them <img>

**Comment by ozross** [comment]
Here is an example of this structure — though not necessarily inline — where the logo at the very beginning becomes the `Skip to Main` link for Accessibility. This allows easier access to the main substance of a document, skipping past all the front-matter such as Cover page(s), Title page, Table of Contents, Lists of Figures/Tables, Glossaries, etc.

<img width="1090" alt="Screenshot 2024-04-01 at 10 52 41 am" src="https://github.com/pdf-association/Deriving-HTML-from-PDF/assets/11621433/3df3cdf1-ada3-4180-957e-232982192c1d">

- It looks like this in the HTML Accessibility tree:

<img width="1368" alt="Screenshot 2024-04-01 at 11 01 47 am" src="https://github.com/pdf-association/Deriving-HTML-from-PDF/assets/11621433/511e05f1-bb52-448d-bd4a-a2052b2aab1e">

- and like this with HTML tagging and attributes shown:

<img width="1149" alt="Screenshot 2024-04-02 at 9 10 05 am" src="https://github.com/pdf-association/Deriving-HTML-from-PDF/assets/11621433/64a0e4b2-9e9c-4ea5-bd0c-6cc16f0e6d6b">

Notice the CSS rule `display:inline-block;` on the `<a>` tag. This is a minor detail that causes the thick blue border around the logo to be the correct size when the link-anchor has focus; e.g. initially, due to `autofocus`. Without that CSS rule, the full logo is still active, though the focus rectangle will not show the correct height.

Presumably for an inline image to show the correct active size, it needs a similar CSS rule.

**Comment by romantoda** [comment]
I think that tagging <Figure> { <Link> {content} }

a.)
Isn’t best pracise and we should encourage  <Link> { <Figure> {content} }
Which derives fine into <a> <figure> <img> </img> <figure> </a> 

The problem is with inline images <P>{ <Link>{ <Figure>}} 

Proposal:
Figures and formulae in “inline mode” - as a child of P containing Link or Reference would be subject of the same derivation as Figure being direct child of P

b.)
Isn’t explicitly disallowed. What would be the use case? If link annotation only covers portion of the image?
But generally I don’t see a problem with following derivation either:
<figure>
	<a href="">
  	<img src="pic.jpg">
	</a>    
  <figcaption>sadfasd</figcaption>
</figure>

**Comment by romantoda** [comment]
check the wording
